### ISSUE TITLE
How to visualize result

### ISSUE THREAD

**Issue by shunnakamu** [eagle-dataset/EagleMeshTransformer#5]
I can see the result video here.
https://eagle-dataset.github.io/

can you provide the visualization code to make this kind of video?
thanks,

**Comment by jacobchristopher** [comment]
Hi,

I'm wondering this as well. Is this repository maintained? If so, could the maintainer provide indication of how to visualize the results. This is somewhat integral to providing a benchmark dataset.

Thanks!

**Comment by SteevenJanny** [comment]
Hello,
Thank both of you for your interest in our paper. I uploaded the script I used for generating the videos. Nothing fancy here, just an animated Matplotlib figure. You'll find the code in the `misc` folder. 

Sorry for the delay, I try to maintain the repo, but struggle to be reactive. I hope the script will be useful to you.
